### ISSUE TITLE
Already existing pivpn profiles don't get displayed

### ISSUE THREAD

**Issue by szaimen** [WeeJeWel/pivpn-web#14]
Hi,

After installing the docker container and logging in with my ssh user, I don't see any of my already existing wireguard profiles.
Is it possible that this is due to me logging in with a user that isn't priviliged to access the files in /etc/wireguard ?
Unfortunately I couldn't find any logs that are of help here.
How could I make this work?
Thanks for your help!

**Comment by WeeJeWel** [comment]
> Is it possible that this is due to me logging in with a user that isn't priviliged to access the files in /etc/wireguard ?

Most likely yes!

**Comment by szaimen** [comment]
Unfortunately chowning the files to this user didn't work, either, so I am a bit clueless now :/

**Comment by szaimen** [comment]
Is there a way to debug this better than just `docker logs -f pivpn-web` ?

**Comment by simonlerpard** [comment]
Does the user have sudo privileges? And if that's the case, have you disabled the password prompt for sudoing?

**Comment by szaimen** [comment]
Yes, this user has sudo privileges but I would prefer to not disable the password prompt for sudoing.

**Comment by simonlerpard** [comment]
I sort of agree with you, but I guess this is a current limitation of this project since it doesn't support interactive inputs. Please correct me if I'm wrong @WeeJeWel.

I think this might be possible to solve though, according to [this issue on the node-ssh project](https://github.com/steelbrain/node-ssh/issues/90#issuecomment-648865629) it should be possible to specify the sudo password as an stdin execOption.

**Comment by 1oh1** [comment]
I got this working on an Oracle Cloud instance which by default doesn't have password authentication set up for SSH. I had to enable password authentication and log in to PiVPN Web via the "root" user for this to work which seemed highly insecure over a HTTP connection so I forked the project and added support for running the server over HTTPS using self-signed or LetsEncrypt certificates

https://github.com/1oh1/pivpn-web

**Comment by simonlerpard** [comment]
> I got this working on an Oracle Cloud instance which by default doesn't have password authentication set up for SSH. I had to enable password authentication and log in to PiVPN Web via the "root" user for this to work which seemed highly insecure over a HTTP connection so I forked the project and added support for running the server over HTTPS using self-signed or LetsEncrypt certificates
> 
> https://github.com/1oh1/pivpn-web

I can't see how that's related to this issue? 😜 I guess there's no need to implement ssl inside this project, since a more common (and easy) way is to go through a reverse proxy to terminate ssl. E.g. using  [Nginx Proxy Manager](https://nginxproxymanager.com/) or similar

**Comment by szaimen** [comment]
> log in to PiVPN Web via the "root" user

That is unfortunately not an option for me and doesn't solve this issue, either. @WeeJeWel can we please reopen this?

**Comment by WeeJeWel** [comment]
> I can't see how that's related to this issue? 😜 I guess there's no need to implement ssl inside this project, since a more common (and easy) way is to go through a reverse proxy to terminate ssl. E.g. using [Nginx Proxy Manager](https://nginxproxymanager.com/) or similar

Yes, a reverse proxy for SSL is the best way to go. One tool, one job.

**Comment by WeeJeWel** [comment]
> > log in to PiVPN Web via the "root" user
> 
> That is unfortunately not an option for me and doesn't solve this issue, either. @WeeJeWel can we please reopen this?

Well, I'm not going to fix it :) Feel free to make a PR though.

**Comment by szaimen** [comment]
Maybe @simonlerpard can help to accomplish this? :) I fear I don't understand nodejs and javascript good enough to be able to implement this :/

**Comment by simonlerpard** [comment]
> Maybe @simonlerpard can help to accomplish this? :) I fear I don't understand nodejs and javascript good enough to be able to implement this :/

I've actually been thinking about it, I just need some spare time 😁👍

**Comment by 1oh1** [comment]
> > I got this working on an Oracle Cloud instance which by default doesn't have password authentication set up for SSH. I had to enable password authentication and log in to PiVPN Web via the "root" user for this to work which seemed highly insecure over a HTTP connection so I forked the project and added support for running the server over HTTPS using self-signed or LetsEncrypt certificates
> > https://github.com/1oh1/pivpn-web
> 
> I guess there's no need to implement ssl inside this project, since a more common (and easy) way is to go through a reverse proxy to terminate ssl. E.g. using [Nginx Proxy Manager](https://nginxproxymanager.com/) or similar

I didn't know about Nginx Proxy Manager. That looks awesome, thanks 👍🏻

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
