### ISSUE TITLE
[Feature Request] Enable/Disable User

### ISSUE THREAD

**Issue by peddaahh** [WeeJeWel/pivpn-web#3]
Enable/Disable user

pivpn -off
pivpn -on

Config isn't deleted

**Comment by WeeJeWel** [comment]
That would be nice but... I don't have that command!

**Comment by peddaahh** [comment]
Hm that's weird...
![Screenshot_1](https://user-images.githubusercontent.com/37550489/108892503-3d9a2a80-7610-11eb-941a-5750501e10f2.png)

**Comment by WeeJeWel** [comment]
Just to be sure, you're using WireGuard?

**Comment by peddaahh** [comment]
Yes definitely

**Comment by peddaahh** [comment]
Connections are all on the wg if so it must be wireguard

![image](https://user-images.githubusercontent.com/37550489/108892818-9c5fa400-7610-11eb-846d-901c70e5a862.png)
![image](https://user-images.githubusercontent.com/37550489/108892901-b7caaf00-7610-11eb-9cc1-ca917f46d8c4.png)
![image](https://user-images.githubusercontent.com/37550489/108893030-e34d9980-7610-11eb-86dc-f1d6b825f67d.png)

**Comment by bySimpson** [comment]
> Hm that's weird...
> ![Screenshot_1](https://user-images.githubusercontent.com/37550489/108892503-3d9a2a80-7610-11eb-941a-5750501e10f2.png)

I can also see these features.

**Comment by WeeJeWel** [comment]
I've updated pivpn (by uninstalling and reinstalling, argh) and now I have them :)

**Comment by WeeJeWel** [comment]
I've looked into how it works and it's possible, just a little hacky to read the current status (read `wg0.conf` and parse comments...)

**Comment by peddaahh** [comment]
Woah okay, but it would be nice just to have some basic UAC features

**Comment by WeeJeWel** [comment]
Yes I agree :)

**Comment by WeeJeWel** [comment]
Working branch: https://github.com/WeeJeWel/pivpn-web/tree/feature/disabled-users

**Comment by WeeJeWel** [comment]
<img width="679" alt="Screenshot 2021-02-23 at 20 45 33" src="https://user-images.githubusercontent.com/319873/108898955-22cbb400-7618-11eb-9805-2a66d7a8d53f.png">

This is now working. I'm going to create a new release.

**Comment by peddaahh** [comment]
Cool gonna try it

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
