### ISSUE TITLE
See who is online

### ISSUE THREAD

**Issue by peddaahh** [WeeJeWel/pivpn-web#4]
You already can see live traffic.

Would be nice if there is just a text if the User has never connected / last connection under the name of the Config.
And then green point at the Icon could replaced to indicate a currently connected user

e.g. if last seen is >60sec or so

**Comment by WeeJeWel** [comment]
I'm sorry but I don't really understand. Could you show an example how it would look like?

**Comment by peddaahh** [comment]
![image](https://user-images.githubusercontent.com/37550489/108903016-1bf37000-761d-11eb-95a3-662eff0fdf5b.png)

**Comment by peddaahh** [comment]
and nvm this last seen already works

**Comment by WeeJeWel** [comment]
There's also already a green icon for connected users.

What am I missing? :)

**Comment by peddaahh** [comment]
But none of my users are connected right now...

![image](https://user-images.githubusercontent.com/37550489/108966757-e0898d80-767e-11eb-9035-d4425a514062.png)

**Comment by WeeJeWel** [comment]
I see. It might be better to show online only if lastSeen < 15 min.

**Comment by peddaahh** [comment]
That would be better yeah

**Comment by WeeJeWel** [comment]
Fixed in v1.1.1.
https://github.com/WeeJeWel/pivpn-web/commit/b9eb9496a07e43557d51c7ad388e16137624def5

**Comment by peddaahh** [comment]
Yea have tried it. Works fine now.

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
