### ISSUE TITLE
Option to disable Gravatar-support

### ISSUE THREAD

**Issue by quotengrote** [WeeJeWel/pivpn-web#6]
Hi,

first of all, Thanks.

Second ;-)

Is there an Option to disable Gravatar-Support?

Wishes
mg

**Comment by WeeJeWel** [comment]
No. Why would you want that? :)

**Comment by quotengrote** [comment]
I have some users who are registered but i dont like to see their avatars.

**Comment by WeeJeWel** [comment]
Haha okay. Feel free to fork, but I'm not going to add this :)
