### ISSUE TITLE
Bug and feedback

### ISSUE THREAD

**Issue by aazam476** [WeeJeWel/pivpn-web#8]
Bug: PiVPN-web does not accept said credentials.

Possible Reason 1: I am using a password with special characters
AND/OR
Possible Reason 2: I am using a 128 character long password.
AND/OR
Possible Reason 3: I use 2FA on my SSH since I open it to the internet
AND/OR
Possible Reason 4: I am accessing the GUI from an external domain.

Example of a Password I would use: PN5tIg7btUXs0T!*&P@Yu5CQRw1XgdJ$t04OS@z#YYfkBh&o7y40P$Jgf1y1zbjmD0W5MtQzWG*7lz@c1ozj5qjh!H4DjKrPTcqsr@9N2Dpbg$j*bumhdVE#YU2smG&u

-----------------------------------------------------------------------------------------------------------------------------

Feedback 1: Make an official docker compose file
- This makes an easy way to edit something you need later on
- Many other dockers have it
- Allows you to add a variable you need very easily

FeedBack 2: Allow us to customize username and password for PiVPN-web interface
- If someone's username and password is breached, their PiVPN-web interface will be safe

Feedback 3: Allow to access config of docker with docker volumes
- Allow easy change to docker if needed without much hassle.

**Comment by WeeJeWel** [comment]
I didn't know about SSH 2FA. How does it work, do you append the OTP to the password?

**Comment by WeeJeWel** [comment]
FYI there's a `docker-compose.yml` file.

**Comment by aazam476** [comment]
> I didn't know about SSH 2FA. How does it work, do you append the OTP to the password?

You need to make changes to some of the SSH files which will ask you for a password, and then a time-based OTP (TOTP). You can learn more about it here.

[https://www.raspberrypi.org/blog/setting-up-two-factor-authentication-on-your-raspberry-pi/](url)

Close to the bottom of the url, there should be a person holding a phone with his TOTP. Behind his phone, on his computer, there should be how terminal (Mac) asks for the TOTP.

**Comment by aazam476** [comment]
> FYI there's a `docker-compose.yml` file.

Where? By any chance, could you add it to the README.md?

**Comment by aazam476** [comment]
Also, what about the other feedback?

**Comment by WeeJeWel** [comment]
> Where? By any chance, could you add it to the README.md?

https://github.com/WeeJeWel/pivpn-web/blob/master/docker-compose.yml


> Also, what about the other feedback?

#2: Might be possible, but we still need a way to access pivpn outside the Docker container.

#3: Which volumes do you want to mount & why? There's no config right now inside the container.

**Comment by aazam476** [comment]
> > Where? By any chance, could you add it to the README.md?
> 
> https://github.com/WeeJeWel/pivpn-web/blob/master/docker-compose.yml
> 
> > Also, what about the other feedback?
> 
> #2: Might be possible, but we still need a way to access pivpn outside the Docker container.
> 
> #3: Which volumes do you want to mount & why? There's no config right now inside the container.

 I would put the link to the docker-compose.yml file at the end or your README.md just so other people won't have to look in issues to find it. Something like this to keep up with your README.md theme.

Docker Compose File
-----------------------------------------------------------------------------------------------------------------------------
[https://github.com/WeeJeWel/pivpn-web/blob/master/docker-compose.yml](url)

About the feedback, what you can do about #2 is make users input their ssh user credentials and the new credentials in the docker-compose.yml file. This way, when a user inputs the new credentials, PiVPN-web will just use the ssh credentials instead. For the 2FA, along with the ssh credentials, you can ask for the SSH 2FA key so PiVPN-web can generate a code for the SSH while inputting the SSH credentials. You can more environment variables to the docker-compose.yml file to ask for all the new needed details.

For #3, mounting the the root directory lets users add or remove files they want in the docker. This might not be useful right now, but it may become useful for a user in the future. Also, from my understanding dockers run a very stripped version of a linux distribution, so they still have a root directory. Please correct me if I am wrong.

**Comment by aazam476** [comment]
Also, thanks for the quick and easy to understand feedback, and for developing this project.

**Comment by WeeJeWel** [comment]
Hm maybe we can let users set an SSH key with 2FA as environment variable, and then the login dialog only asks for the 2FA password.

**Comment by WeeJeWel** [comment]
Or easier: create a read-only volume to `~/.ssh/`...

**Comment by aazam476** [comment]
> Hm maybe we can let users set an SSH key with 2FA as environment variable, and then the login dialog only asks for the 2FA password.

The more security the better, especially with VPNs. Because of this, maybe we can ask for the custom username and password and 2FA?

**Comment by aazam476** [comment]
> Or easier: create a read-only volume to `~/.ssh/`...

Sorry, but I don't understand. Could you please expand on this?

**Comment by aazam476** [comment]
We could also let users input their SSH 2FA authentication key, which from it, you could generate the TOTP needed to authenticate. This also allows for you to build in your own 2FA into the login process for PiVPN-web, to make the web interface more secure.

**Comment by aazam476** [comment]
So any update on the 2FA situation?

**Comment by WeeJeWel** [comment]
You're free to make a PR. It's not really on my TODO list as of now.

**Comment by aazam476** [comment]
Ok. Also, I am hosting another server in Google Cloud. The problem is that there is no SSH password, but SSH keys. How would PiVPN-web access that server?

**Comment by WeeJeWel** [comment]
Using SSH keys is not currently possible.

**Comment by aazam476** [comment]
Hi, its been a while. I may have found a solution to my problem. How about we can merge the pivpn docker (https://github.com/InnovativeInventor/docker-pivpn), meaning that we combine both dockers and run this GUI and pivpn in the same docker. This way there won't be any SSH issues. If you aren't ready to do this, please feel free to tell me, and I can fork this project and make a pull request when I'm done.

**Comment by aazam476** [comment]
Sorry for the sudden question. I also had another one, though. Is there any way this docker can be migrated to a debian docker. Again, if not, please feel free to tell me, and I will try to migrate it myself using a fork.

**Comment by WeeJeWel** [comment]
> Hi, its been a while. I may have found a solution to my problem. How about we can merge the pivpn docker (https://github.com/InnovativeInventor/docker-pivpn), meaning that we combine both dockers and run this GUI and pivpn in the same docker. This way there won't be any SSH issues. If you aren't ready to do this, please feel free to tell me, and I can fork this project and make a pull request when I'm done.

Feel free to fork and do that. I personally am thinking of creating a new project that only uses WireGuard inside docker + this web interface, because OpenVPN isn't supported now anyway.

**Comment by WeeJeWel** [comment]
Hey guys! PiVPN Web has been archived, and its successor is [wg-easy](https://github.com/WeeJeWel/wg-easy).

It is a much better and simpler solution because it has WireGuard pre-installed, next to the Web UI you're familiar with. Additionally, you can set a custom password, so no more SSH dependency.
