### ISSUE TITLE
[RFC] Add favicon / Apple icon

### ISSUE THREAD

**Issue by Killator** [WeeJeWel/pivpn-web#9]
Hi emile,

Thanks you for your "beautiful & easy to use" interface ! 👌🏻
I use it very often to manage/monitor my devices 👍🏻

I have a little suggestion to improve the user experience: could you please integrate [a favicon and/or a Apple icon](https://www.collectiveray.com/joomla/joomla-tips-and-tricks/94-creating-a-favicon-and-apple-icon-for-your-website.html) on your projet ?
This will allow users to create a "beautiful WebClip/Shortcut" 😉 

Thank you for the time you can give to my request.

![IMG_4026](https://user-images.githubusercontent.com/31735023/114313085-665d7d00-9af5-11eb-888d-0e7c3ac12ff3.jpg)

**Comment by WeeJeWel** [comment]
Would be nice indeed. I'll think about a logo.

Please consider making a donation as well:)

**Comment by WeeJeWel** [comment]
Fixed in v1.1.2!

**Comment by Killator** [comment]
Wow... Light speed delivery ! Everything is up-to-date (Watchtower) and working fine this morning ! 👌🏻

Thank you so much and greetings from France 😷

![image](https://user-images.githubusercontent.com/31735023/114340495-f59b7c80-9b57-11eb-8798-caef82ff5779.jpeg)

**Comment by WeeJeWel** [comment]
Thanks for your [donation](https://github.com/sponsors/WeeJeWel?frequency=one-time&sponsor=WeeJeWel), by the way ;-)
